SELECT [ClientID],
    [Status],
    [CustomerAge],
    [Gender],
    [DependentCount],
    [Education],
    [MaritalStatus],
    [IncomeCategory],
    [CardCategory],
    [MonthsOnBook],
    [TotalRelationshipCount],
    [MonthsInactiveIn12Month],
    [ContactsCountIn12Month],
    [CreditLimit],
    [TotalREvolvingBalance],
    [AvgOpenToBuy],
    [TotalTransAmt],
    [TotalTransCT],
    [AvgUtilizationRatio]
FROM dbo.DataWarehouse;